# Setup
title:               Hildegard
tagline:             '1877 bibliography on the life and works of Hildegard of Bingen (1098-1179)'
description:         'Hildegard - 1877 bibliography'
url:                 http://chrisgeroux.xyz # URL with domain name of site e.g. https://mysite.com, should not contain trailing "/"
baseurl:             /hildegard # base url of site, could be '/' if in the web root directory or "/subdir" if a sub directory
#paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Author name
  url:               author url
  email:             author email

# Gems
#plugins:
#  - jekyll-sitemap
#  - jekyll-paginate

# Custom vars
google_analytics_id: UA-203459783-1

collections:
  sections:
    output: true
  monographical:
    output: true
  historical-biographical:
    output: true
  medical:
    output: true
  general:
    output: true
  relics:
    output: true

